- name: Install power management tooling (Fedora)
  become: true
  when: "ansible_distribution == 'Fedora' and 'fedora_variant_workstation' in group_names" 
  ansible.builtin.package:
    name:
      - tlp
      - powertop

- name: Install power management tooling (Silverblue)
  when: "ansible_distribution == 'Fedora' and 'fedora_variant_silverblue' in group_names" 
  community.general.rpm_ostree_pkg:
    name:
      - tlp

- name: Disable powerprofiles daemon
  become: true
  ansible.builtin.systemd:
    name: power-profiles-daemon
    state: stopped
    masked: true
    enabled: false

- name: Enable TLP
  become: true
  ansible.builtin.systemd:
    name: tlp
    enabled: true
