- name: Ensure dbus-run-session binary is present
  become: true
  ansible.builtin.package:
    name:
      - "{{ dbus_run_session_package }}"
    state: present

- name: Enable experimental features for GDM # noqa no-changed-when
  ansible.builtin.shell: dbus-run-session bash -c "dconf write /org/gnome/mutter/experimental-features \"['scale-monitor-framebuffer', 'variable-refresh-rate']\" "
  become: true
  become_user: gdm
  become_flags: ""

- name: Enable experimental features for ourselves # noqa no-changed-when
  ansible.builtin.command: dconf write /org/gnome/mutter/experimental-features "['scale-monitor-framebuffer', 'variable-refresh-rate']"

- name: Copy our current monitor configuration to GDM config
  become: true
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.config/monitors.xml"
    dest: "/var/lib/gdm/.config/monitors.xml"
    owner: gdm
    group: gdm
    mode: "0644"
