- name: Ensure dbus-run-session binary is present (Fedora)
  become: true
  when: "ansible_distribution == 'Fedora' and 'fedora_variant_workstation' in group_names" 
  ansible.builtin.package:
    name:
      - "{{ dbus_run_session_package }}"
    state: present

- name: Ensure dbus-run-session binary is present (Silverblue)
  become: true
  when: "ansible_distribution == 'Fedora' and 'fedora_variant_silverblue' in group_names" 
  community.general.rpm_ostree_pkg:
    name:
      - "{{ dbus_run_session_package }}"
    state: present

#- name: Enable fractional scaling for GDM # noqa no-changed-when
#  ansible.builtin.shell: dbus-run-session bash -c "dconf write /org/gnome/mutter/experimental-features \"['scale-monitor-framebuffer']\" "
#  become: true
#  become_user: gdm
#  become_flags: ''

- name: Enable fractional scaling for GDM
  ansible.builtin.copy:
    src: files/99-scale-monitor-framebuffer
    dest: /etc/dconf/db/gdm.d/
    mode: '0644'

- name: Enable fractional scaling for users
  ansible.builtin.copy:
    src: files/99-scale-monitor-framebuffer
    dest: /etc/dconf/db/local.d/
    mode: '0644'

#- name: Copy our current monitor configuration to GDM config
#  become: true
#  ansible.builtin.copy:
#    src: "{{ ansible_env.HOME }}/.config/monitors.xml"
#    dest: "/var/lib/gdm/.config/monitors.xml"
#    owner: gdm
#    group: gdm
#    mode: '0644'
