- hosts: [all]
  pre_tasks:
    - name: End play if not on Ubuntu or Fedora
      meta: end_host
      tags: [always]
      when:
        - ansible_facts['distribution'] != "Fedora" and ansible_facts['distribution'] != "Ubuntu"
    - name: Gather package facts
      tags: [always]
      ansible.builtin.package_facts:
        manager: auto
  roles:
    - { role: base, tags: [base] }
    - role: framework
      tags: [framework]
      when:
        - ansible_system_vendor == "Framework"
        - ansible_product_name == "Laptop"
