- hosts: [all]
  tags: [always]
  pre_tasks:
    - name: End play if not on Ubuntu or Fedora
      meta: end_host
      when:
        - ansible_facts['distribution'] != "Fedora" and ansible_facts['distribution'] != "Ubuntu"
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
  roles:
    - { role: base, tags: [base] }
    - role: framework
      tags: [framework]
      when:
        - ansible_system_vendor == "Framework" and ansible_product_name == "Laptop"
