- hosts: [all]
  pre_tasks:
    - name: End play if not on MacOS, Ubuntu or Fedora
      meta: end_host
      tags: [always]
      when:
        - ansible_system != 'Darwin' and ansible_facts['distribution'] != "Fedora" and ansible_facts['distribution'] != "Ubuntu"
    - name: Gather package facts
      tags: [always]
      ansible.builtin.package_facts:
        manager: auto
      when: ansible_system == 'Linux'
    - name: Set is_graphical fact
      ansible.builtin.set_fact:
        is_graphical: "{{ (ansible_facts['distribution'] == 'Fedora' and 'fedora-release-workstation' in ansible_facts.packages) or (ansible_facts['distribution'] == 'Ubuntu' and 'ubuntu-desktop' in ansible_facts.packages) }}"
  tasks:
    - include_role:
        name: base
      tags: [base]
    - include_role:
        name: framework
      tags: [framework]
      when:
        - ansible_system_vendor == "Framework"
        - ansible_product_name == "Laptop"
    - include_role:
        name: graphical
      tags: [graphical]
      when: is_graphical
