---

- name: Drop atuin config file
  ansible.builtin.copy:
    src: files/atuin/config.toml
    dest: "{{ ansible_env.HOME }}/.config/atuin/"
    mode: '0644'

- name: Drop atuin key file
  ansible.builtin.copy:
    src: files/atuin/key
    dest: "{{ ansible_env.HOME }}/.local/share/atuin/"
    mode: '0644'

- name: Drop atuin bash config snippet
  ansible.builtin.copy:
    src: files/atuin/10-atuin
    dest: "{{ bash_config_dropins_dir }}/"
    mode: '0644'
