---
# Set up openshift tooling

- name: Drop kubectl alias in bashrc snippet
  ansible.builtin.copy:
    src: files/openshift/08-kubectl-to-k
    dest: "{{ bash_config_dropins_dir }}/"
    mode: '0644'
