- name: Ensure VSCode repository is present (Fedora)
  when: ansible_distribution == 'Fedora'
  become: true
  ansible.builtin.yum_repository:
    state: present
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Visual Studio Code (Mutable)
  when: is_mutable is true
  become: true
  ansible.builtin.package:
    name:
      - code
    state: present

- name: Install Visual Studio Code (Silverblue)
  when: "'fedora_variant_silverblue' in group_vars"
  become: true
  community.general.rpm_ostree_pkg:
    name:
      - code
    state: present
