#- name: Enable proletarius101/firefox-nightly COPR repository (Fedora)
#  become: true
#  ansible.builtin.copy:
#    src: _copr:copr.fedorainfracloud.org:proletarius101:firefox-nightly.repo
#    dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:proletarius101:firefox-nightly.repo
#    mode: '0644'
#  when: ansible_distribution == "Fedora"

#- name: Install media dependencies for firefox-nightly (Fedora)
#  become: true
#  ansible.builtin.package:
#    name:
#      - gstreamer1-libav
#      - gstreamer1-vaapi
#      - gstreamer1-plugins-good
#      - gstreamer1-plugins-good-extras
#      - gstreamer1-plugins-ugly
#  when: ansible_distribution == "Fedora"

#- name: Install firefox-nightly package from COPR repository (Fedora)
#  become: true
#  ansible.builtin.package:
#    name:
#      - firefox-nightly
#  when: ansible_distribution == "Fedora"

- name: Add Firefox nightly flatpak repo
  community.general.flatpak_remote:
    name: firefox-nightly
    state: present
    flatpakrepo_url: https://proletarius101.gitlab.io/firefox-nightly-flatpak
  
- name: Add Firefox nightly flatpak
  community.general.flatpak:
    name: org.mozilla.FirefoxNightly
    remote: firefox-nightly
    state: present
