- name: Add Firefox nightly flatpak repo
  ansible.builtin.copy:
    src: ff-nightly/firefox-nightly.flatpakrepo
    dest: "{{ etc_dir }}/flatpak/remotes.d/firefox-nightly.flatpakrepo"
    mode: '0644'

- name: Add Firefox nightly flatpak repo to /etc (Silverblue)
  when: "'fedora_variant_silverblue' in group_names"
  ansible.builtin.copy:
    src: ff-nightly/firefox-nightly.flatpakrepo
    dest: "{{ etc_dir }}/flatpak/remotes.d/firefox-nightly.flatpakrepo"
    mode: '0644'
