#- name: Enable proletarius101/firefox-nightly COPR repository (Fedora)
#  become: true
#  ansible.builtin.copy:
#    src: _copr:copr.fedorainfracloud.org:proletarius101:firefox-nightly.repo
#    dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:proletarius101:firefox-nightly.repo
#    mode: '0644'
#  when: ansible_distribution == "Fedora"

#- name: Install media dependencies for firefox-nightly (Fedora)
#  become: true
#  ansible.builtin.package:
#    name:
#      - gstreamer1-libav
#      - gstreamer1-vaapi
#      - gstreamer1-plugins-good
#      - gstreamer1-plugins-good-extras
#      - gstreamer1-plugins-ugly
#  when: ansible_distribution == "Fedora"

#- name: Install firefox-nightly package from COPR repository (Fedora)
#  become: true
#  ansible.builtin.package:
#    name:
#      - firefox-nightly
#  when: ansible_distribution == "Fedora"

- name: Ensure Flatpak remotes directory is present
  become: true
  ansible.builtin.file:
    path: "{{ etc_dir }}/flatpak/remotes.d"
    state: directory
    mode: '0755'

- name: Add Firefox nightly flatpak repo
  ansible.builtin.copy:
    src: ff-nightly/firefox-nightly.flatpakrepo
    dest: "{{ etc_dir }}/flatpak/remotes.d/firefox-nightly.flatpakrepo"
    mode: '0644'

- name: Add Firefox nightly flatpak repo to /etc (Silverblue)
  when: "'fedora_variant_silverblue' in group_names"
  ansible.builtin.copy:
    src: ff-nightly/firefox-nightly.flatpakrepo
    dest: "/etc/flatpak/remotes.d/firefox-nightly.flatpakrepo"
    mode: '0644'
  
# TODO: BUG does not properly install within container env
- name: Install Firefox nightly flatpak
  community.general.flatpak:
    name: org.mozilla.FirefoxNightly
    remote: firefox-nightly
    state: present
