- name: Install essential Gnome apps
  become: true
  when: is_mutable is true
  ansible.builtin.package:
    name:
      - gnome-tweaks
      - gnome-extensions-app
    state: present

- name: Install essential Gnome apps
  when: is_mutable is false
  community.general.rpm_ostree_pkg:
    name:
      - gnome-extensions-app
      - gnome-tweaks

- name: Ensure polkit rules directory exists
  become: true
  ansible.builtin.file:
    src: "{{ etc_dir }}/polkit-1/rules.d"
    state: directory
    mode: '0755'

- name: Drop Polkit rules file
  become: true
  ansible.builtin.copy:
    src: polkit/45-domain-admins-have-root.rules
    dest: "{{ etc_dir }}/polkit-1/rules.d/45-domain-admins-have-root.rules"
    mode: '0644'

# A bunch of settings tweaks that normally would require Gnome Tweaks or spelunking in settings
# but that we can do by hand since we know how to use dconf

- name: Ensure dconf db local.d directory exists
  become: true
  ansible.builtin.file:
    src: "{{ etc_dir }}/dconf/db/local.d"
    state: directory
    mode: '0755'

- name: Set up preferred Gnome settings
  become: true
  ansible.builtin.copy:
    src: dconf/99-gnome-defaults
    dest: "{{ etc_dir }}/dconf/db/local.d/"
    mode: '0644'
