---
# tasks file for graphical

- name: Check if Secure Boot is enabled
  become: true
  ansible.builtin.command: mokutil --sb-state
  changed_when: false
  register: secureboot_status

- name: Register SecureBoot fact
  ansible.builtin.set_fact:
    secureboot_enabled: "{{ 'SecureBoot enabled' in secureboot_status.stdout }}"

- name: Install quassel client
  become: true
  ansible.builtin.package:
    name: quassel-client
    state: present

- include_tasks: gnome.yml
- include_tasks: discord.yml
- include_tasks: code.yml
- include_tasks: ff-nightly.yml
- include_tasks: systemd.yml
- include_tasks: swap.yml
