---
# tasks file for graphical

- name: Install quassel client
  become: yes
  ansible.builtin.package:
    name: quassel-client
    state: latest

- include: gnome.yml
- include: discord.yml
- include: code.yml
- include: ff-nightly.yml
- include: systemd.yml
