---
# tasks file for graphical

- name: Install quassel client
  become: true
  ansible.builtin.package:
    name: quassel-client
    state: present

- include_tasks: gnome.yml
- include_tasks: discord.yml
- include_tasks: code.yml
- include_tasks: ff-nightly.yml
- include_tasks: systemd.yml
- include_tasks: swap.yml
