---
# tasks file for graphical

- name: Ensure flathub remote is available
  community.general.flatpak_remote:
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    enabled: true
    method: system
    name: flathub
    state: present

#- name: Install quassel client
#  become: true
#  community.general.flatpak:
#    name: org.quassel_irc.QuasselClient
#    state: present
#    remote: flathub

- include: gnome.yml
- include: discord.yml
- include: code.yml
- include: ff-nightly.yml
- include: systemd.yml
