---
# tasks file for graphical

- name: Install quassel client
  become: true
  community.general.flatpak:
    name: org.quassel_irc.QuasselClient
    state: present
    remote: flathub

- include: gnome.yml
- include: discord.yml
- include: code.yml
- include: ff-nightly.yml
- include: systemd.yml
