---
# tasks file for graphical

- name: Check if Secure Boot is enabled
  become: true
  ansible.builtin.command: mokutil --sb-state
  changed_when: false
  register: secureboot_status

- name: Register SecureBoot fact
  ansible.builtin.set_fact:
    secureboot_enabled: "{{ 'SecureBoot enabled' in secureboot_status.stdout }}"

- name: Install RPMFusion Free repository
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when:
    - ansible_facts['distribution'] == 'Fedora'
    - rpmfusion-free-release in ansible_facts.packages

- name: Install RPMFusion Nonfree repository
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when:
    - ansible_facts['distribution'] == 'Fedora'
    - rpmfusion-nonfree-release in ansible_facts.packages

- name: Configure GNOME
  ansible.builtin.include_tasks: gnome.yml

- name: Configure visual studio code
  ansible.builtin.include_tasks: code.yml

- name: Configure systemd
  ansible.builtin.include_tasks: systemd.yml
