---
# tasks file for graphical

- name: Ensure Flatpak remotes directory is present
  become: true
  ansible.builtin.file:
    path: "{{ etc_dir }}/flatpak/remotes.d"
    state: directory
    mode: '0755'

- name: Ensure flathub remote is available
  ansible.builtin.get_url:
    dest: "{{ etc_dir }}/flatpak/remotes.d/flathub.flatpakrepo"
    url: https://flathub.org/repo/flathub.flatpakrepo
    mode: '0644'

- include_tasks: gnome.yml
- include_tasks: code.yml
- include_tasks: ff-nightly.yml
- include_tasks: systemd.yml
