#!/bin/bash

source ~/.profile

~/.fehbg &

redshift -l 39.98389:-75.14986 -t 6500:5000 &

compton -CGcf -t -4 -l -2 -r4 -o .55 -D2 --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --sw-opti &

light-locker &

dunst &

pulseaudio --daemon
