#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width                5
bspc config window_gap                  15
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true

bspc desktop 11 -l monocle
bspc rule -a gimp floating=on

wmname LG3D

nitrogen --restore

sxhkd &

compton -b

light-locker &

