#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11

bspc config border_width                2
bspc config top_padding                 20
bspc config window_gap                  12
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true

bspc desktop 11 -l monocle
bspc rule -a quasselclient desktop=^11
bspc rule -a gimp floating=on

wmname LG3D

~/dotfiles/dzen/panel.sh &

