---
# vars file for base

local_bin_dir: "{{ ansible_env.HOME }}/.local/bin/"

bash_config_dir: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(lookup('env', 'HOME') + '/.config', True) }}/bash_config"

bash_config_dropins_dir: "{{ bash_config_dir }}/snippets"
