---
- name: Refresh package repositories
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution == 'Ubuntu'

- name: Refresh Homebrew
  when: ansible_system == 'Darwin'
  community.general.homebrew:
    upgrade_all: true

- name: Install common base set of packages
  become: true
  ansible.builtin.package:
    name:
      - htop
      - neovim
      - ripgrep
      - rsync
      - unzip
      - "{{ xz_pkg_name }}"
      - curl
      - wget
      - "{{ netcat_pkg_name }}"
      - ca-certificates
      - bat
    state: present

- name: Install SSH tools
  become: true
  when: ansible_system == 'Linux'
  ansible.builtin.package:
    state: present
    name:
      - "{{ openssh_client_pkg_name }}"

- name: Ensure .ssh directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Install development tools
  become: true
  when: ansible_system == 'Linux'
  ansible.builtin.package:
    state: present
    name:
      - make
      - "{{ development_tools }}"

- name: Install GNU coreutils
  when: ansible_system == 'Darwin'
  ansible.builtin.package:
    state: present
    name:
      - binutils
      - coreutils
      - gnu-tar

- name: Drop oh-my-posh config
  ansible.builtin.copy:
    src: omp.json
    dest: "{{ config_dir }}/omp.json"
    mode: "0644"
