- name: Install dotnet SDK 6.0 (Fedora)
  when: ansible_distribution == "Fedora"
  become: true
  ansible.builtin.package:
    name:
      - dotnet-sdk-6.0
    state: present

- name: Install Microsoft signing key and repository (Ubuntu)
  when: ansible_distribution == "Ubuntu"
  become: true
  ansible.builtin.apt:
    deb: "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"

- name: Install Dotnet SDK 6.0 (Ubuntu)
  when: ansible_distribution == "Ubuntu"
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
      - dotnet-sdk-6.0
    state: present
