- name: Ensure Go bashrc snippet is dropped in place
  ansible.builtin.template:
    src: go/08-gopath.j2
    dest: "{{ bash_config_dropins_dir }}/08-gopath"
    mode: '0644'

- name: Ensure Go is installed
  become: true
  ansible.builtin.package:
    name:
      - golang
    state: present
