- name: Ensure Hashicorp repository GPG key is imported (Ubuntu)
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Ensure Hashicorp repository is available (Ubuntu)
  become: true
  ansible.builtin.apt_repository:
    state: present
    update_cache: yes
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
  when: ansible_distribution == "Ubuntu"

- name: Ensure Hashicorp stable repository is available and enabled (Fedora)
  become: true
  ansible.builtin.yum_repository:
    state: present
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  when: ansible_distribution == "Fedora"

- name: Ensure Hashicorp test repository is available (Fedora)
  become: true
  ansible.builtin.yum_repository:
    state: present
    name: hashicorp-test
    description: Hashicorp Test - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/test
    enabled: no
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  when: ansible_distribution == "Fedora"

- name: Install necessary Hashicorp tools
  become: true
  ansible.builtin.package:
    name:
      - terraform
      - packer
    state: present
