- name: Ensure Hashicorp stable repository is available and enabled
  become: true
  ansible.builtin.yum_repository:
    state: present
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  when: ansible_distribution == "Fedora"

- name: Ensure Hashicorp test repository is available
  become: true
  ansible.builtin.yum_repository:
    state: present
    name: hashicorp-test
    description: Hashicorp Test - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/test
    enabled: no
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  when: ansible_distribution == "Fedora"

- name: Install necessary Hashicorp tools
  become: true
  ansible.builtin.package:
    name:
      - terraform
      - packer
    state: present
