- name: Ensure podman is installed
  become: true
  ansible.builtin.package:
    name: podman
    state: present
  when: "'fedora_variant_silverblue' not in group_names" # Silverblue already has it

- name: Ensure Podman is configured to prefer GCR mirror over Docker Hub
  become: true
  ansible.builtin.copy:
    src: files/podman/001-gcr-mirror.conf
    dest: /etc/containers/registries.conf.d/
    mode: '0644'

- name: Fetch docker-compose releases from Github
  ansible.builtin.uri:
    url: https://api.github.com/repos/docker/compose/releases
    return_content: yes
  register: docker_compose_releases

- name: Fetch sha256sum of latest docker-compose release
  ansible.builtin.uri:
    url: "{{ docker_compose_releases.json | json_query('[?prerelease==`false`] | [0].assets[?name==`docker-compose-linux-x86_64.sha256`].browser_download_url') | first }}"
    return_content: yes
  register: docker_compose_checksum

- name: Download and install latest docker-compose release
  ansible.builtin.get_url:
    dest: "/usr/bin/docker-compose"
    mode: 0755
    url: "{{ docker_compose_releases.json | json_query('[?prerelease==`false`] | [0].assets[?name==`docker-compose-linux-x86_64`].browser_download_url') | first }}"
    checksum: "sha256:{{ docker_compose_checksum.content.split(' ')[0] }}"
