- name: Ensure podman is installed
  become: true
  ansible.builtin.package:
    name: podman
    state: latest

- name: Ensure podman.socket is enabled and started
  ansible.builtin.systemd:
    name: podman.socket
    enabled: yes
    state: started
    scope: user # TODO: will this work via SSH?

- name: Fetch docker-compose releases from Github
  ansible.builtin.uri:
    url: https://api.github.com/repos/docker/compose/releases
    return_content: yes
  register: docker_compose_releases

- name: Fetch sha256sum of latest docker-compose release
  ansible.builtin.uri:
    url: "{{ docker_compose_releases.json | json_query('[0].assets[?name==`docker-compose-Linux-x86_64.sha256`].browser_download_url') | first }}"
    return_content: yes
  register: docker_compose_checksum

- name: Download and install latest docker-compose release
  ansible.builtin.get_url:
    dest: "{{ local_bin_dir }}/docker-compose"
    mode: 0755
    url: "{{ docker_compose_releases.json | json_query('[0].assets[?name==`docker-compose-Linux-x86_64`].browser_download_url') | first }}"
    checksum: "sha256:{{ docker_compose_checksum.content.split(' ')[0] }}"

- name: Drop bashrc snippet for Podman
  ansible.builtin.copy:
    src: files/podman/07-podman
    dest: "{{ bash_config_dropins_dir }}/"
