- name: Ensure podman is installed
  become: true
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure Podman is configured to prefer GCR mirror over Docker Hub
  become: true
  ansible.builtin.copy:
    src: files/podman/001-gcr-mirror.conf
    dest: /etc/containers/registries.conf.d/
    mode: '0644'
