- name: Ensure systemd user etc dir is available
  ansible.builtin.file:
    path: "{{ etc_dir }}/systemd/user"
    state: directory
    mode: '0755'

- name: Ensure ansible-pull timer is available
  ansible.builtin.copy:
    src: pull/dotfiles-ansible-pull.timer
    dest: "{{ etc_dir }}/systemd/user/"
    mode: '0644'

- name: Ensure ansible-pull service is available
  ansible.builtin.copy:
    src: pull/dotfiles-ansible-pull.service
    dest: "{{ etc_dir }}/systemd/user/"
    mode: '0644'

- name: Ensure systemd user preset dir is available
  ansible.builtin.file:
    path: "{{ etc_dir }}/systemd/user-preset"
    state: directory
    mode: '0755'

- name: Ensure ansible-pull timer preset is present
  ansible.builtin.copy:
    src: pull/dotfiles-ansible-pull.preset
    dest: "{{ etc_dir }}/systemd/user-preset/"
    mode: '0644'

- name: Ensure that rpm-ostree automatic updates are enabled
  when: "'fedora_variant_silverblue' in group_names"
  block:
    - name: Ensure rpm-ostree configuration is present
      ansible.builtin.copy:
        src: pull/rpm-ostreed.conf
        dest: "{{ etc_dir }}/rpm-ostreed.conf"
        mode: '0644'

    - name: Ensure times.target.wants is available
      ansible.builtin.file:
        path: "{{ etc_dir }}/systemd/system/timers.target.wants"
        state: directory
        mode: '0755'

    - name: ensure rpm-ostreed-automatic.timer is enabled
      ansible.builtin.file:
        src: /usr/lib/systemd/system/rpm-ostreed-automatic.timer
        dest: "{{ etc_dir }}/systemd/system/timers.target.wants/rpm-ostreed-automatic.timer"
        state: link

    - name: Ensure rpm-ostreed-automatic.service.d is available
      ansible.builtin.file:
        path: "{{ etc_dir }}/systemd/system/rpm-ostreed-automatic.service.d"
        state: directory
        mode: '0755'

    - name: drop override configuration to ensure this only starts on unmetered connections
      ansible.builtin.copy:
        src: pull/10-override-rpm-ostreed-automatic.conf
        dest: "{{ etc_dir }}/systemd/system/rpm-ostreed-automatic.service.d/"
        mode: '0644'

- name: Ensure ansible-pull cronjob is in place (MacOS)
  when: ansible_system == 'Darwin'
  ansible.builtin.cron:
    name: ansible-pull
    job: "/usr/local/bin/ansible-pull --accept-host-key --checkout main --tags base --url 'https://github.com/SriRamanujam/dotfiles.git' --directory {{ ansible_env.HOME }}/.dotfiles --inventory 'localhost,' --connection=local --private-key {{ ansible_env.HOME }}/.ssh/id_rsa"
    state: present
    minute: "43"
    hour: "*/2"
    day: "*"
    weekday: "*"
    month: "*"
