- name: Ensure systemd user etc dir is available
  ansible.builtin.file:
    path: "{{ etc_dir }}/systemd/user"
    state: directory
    mode: '0755'

- name: Ensure ansible-pull timer is available
  ansible.builtin.copy:
    src: pull/dotfiles-ansible-pull.timer
    dest: "{{ etc_dir }}/systemd/user/"
    mode: '0644'

- name: Ensure ansible-pull service is available
  ansible.builtin.copy:
    src: pull/dotfiles-ansible-pull.service
    dest: "{{ etc_dir }}/systemd/user/"
    mode: '0644'

- name: Ensure systemd user preset dir is available
  ansible.builtin.file:
    path: "{{ etc_dir }}/systemd/user-preset"
    state: directory
    mode: '0755'

- name: Ensure ansible-pull timer preset is present
  ansible.builtin.copy:
    src: pull/dotfiles-ansible-pull.preset
    dest: "{{ etc_dir }}/systemd/user-preset/"
    mode: '0644'

- name: Ensure ansible-pull cronjob is in place (MacOS)
  when: ansible_system == 'Darwin'
  ansible.builtin.cron:
    name: ansible-pull
    job: "/usr/local/bin/ansible-pull --accept-host-key --checkout main --tags base --url 'https://github.com/SriRamanujam/dotfiles.git' --directory {{ ansible_env.HOME }}/.dotfiles --inventory 'localhost,' --connection=local --private-key {{ ansible_env.HOME }}/.ssh/id_rsa"
    state: present
    minute: "43"
    hour: "*/2"
    day: "*"
    weekday: "*"
    month: "*"
