- name: Install Python 3
  become: true
  ansible.builtin.package:
    name:
      - python3
    state: present

- name: Install Python 3 dev libraries (Linux)
  become: true
  when: ansible_system == 'Linux'
  ansible.builtin.package:
    name:
      - "{{ python3_devel }}"
    state: present

- name: Determine if Poetry is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/poetry"
  register: poetry_binary

- name: Fetch Poetry
  ansible.builtin.uri:
    url: https://install.python-poetry.org
    return_content: yes
  register: poetry_installer
  when: not poetry_binary.stat.exists

- name: Run Poetry installer
  ansible.builtin.shell: # noqa command-instead-of-shell
    cmd: python3 - --yes
    stdin: "{{ poetry_installer.content }}"
  when: poetry_installer.content is defined

- name: Drop bashrc snippet for Python
  ansible.builtin.copy:
    src: files/python/07-poetry
    dest: "{{ bash_config_dropins_dir }}/"
    mode: '0644'
